### ISSUE TITLE
HTTP

### ISSUE THREAD

**Issue by ycdeng** [ycdeng/fakeShop#5]
在动手之前, 必须先了解http
6.22 晚上进行答疑
提前了解以下概念
1. session
2. cookie
3. URL, verb
4. Request
5. Request header
6. Response
7. Response header
8. 状态码
9. 重定向
10. chrome 调试工具查看请求
11. 200, 304, 404

**Comment by zhenailuoye1** [comment]
基本概念大体清楚，对http有了初步的印象
