### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by ycdeng** [ycdeng/fakeShop#6]
原生js做网站基本是不现实的, jquery是对原生js的一些简单封装.
登陆页面所有动作全部使用jquery

了解jquery, 并写一个页面, 试用jquery的几个函数.
小练习
1. 增加点击事件
2. 用jquery控制样式
3. 增加定时事件
4. 用jquery操作html块
5. ajax
6. 综合使用jquery, 做一个小工具

**Comment by zhenailuoye1** [comment]
增加点击时间是什么意思？是指“点击事件”吗？

**Comment by ycdeng** [comment]
已更新

**Comment by zhenailuoye1** [comment]
已解决
