### ISSUE TITLE
scss , less, sass

### ISSUE THREAD

**Issue by ycdeng** [ycdeng/fakeShop#7]
原生css不利于工程化, scss, less, sass就是用来写出更好维护的css代码

请简单了解以上2个工具..

并选择一个, 在项目中使用

**Comment by zhenailuoye1** [comment]
scss

**Comment by zhenailuoye1** [comment]
选择scss的理由：
一、关于scss和sass
scss和sass是同一种css预处理语言，主要区别在于语法格式上不同。由于sass主要依赖缩进而舍弃了{}，空格至关重要，虽然看上去更加简洁，减少了代码量，但是很可能由于对空格的疏忽而引起各种问题。其次sass对已有的css代码不兼容。
二、关于scss/sass和less
less代码风格与原生css更接近，优势在于学习成本低，但是其功能不如scss/sass强大：
1.less占用了 @at-rule 关键字作为了变量标识符，使得功能扩展性大大降低。
2.less是没有函数支持的，例如scss/sass支持条件语句，可以使用if{}else{},for{}循环等等，而less不支持。

综上分析，在兼容、扩展等方面权衡，选择scss能更好地维护的css代码

**Comment by zhenailuoye1** [comment]
那么问题来了，既然scss和sass是同一种东西，那么选择scss不也就是选择了sass么。。。

**Comment by ycdeng** [comment]
对, 我只是大致去搜了一下, 没仔细了解. 
scss 和 sass是同一个工具.

OK, 那选择scss, 我个人也不太喜欢用缩进代替大括号
